# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='time_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
