# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0003_organization_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
