# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('child', '0004_organization_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbe', models.PositiveIntegerField(default=0)),
                ('category', models.ManyToManyField(to='child.categories')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
