# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0005_vacancies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='numbe',
            new_name='number',
        ),
    ]
