# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0006_auto_20180531_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('age_group', models.CharField(max_length=40)),
                ('topic', models.CharField(blank=True, max_length=50)),
                ('site', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('time', models.CharField(blank=True, max_length=50)),
                ('volunteer_app', models.CharField(blank=True, max_length=50)),
                ('volunteer_app_deadline', models.CharField(blank=True, max_length=50)),
                ('volunteer_time', models.CharField(blank=True, max_length=100)),
                ('student_app', models.CharField(blank=True, max_length=50)),
                ('student_app_deadline', models.CharField(blank=True, max_length=50)),
                ('nomination', models.CharField(blank=True, max_length=50)),
                ('nomination_deadline', models.CharField(blank=True, max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('scholarship_app', models.CharField(blank=True, max_length=50)),
                ('scholarship_app_deadline', models.CharField(blank=True, max_length=50)),
                ('donations_accepted', models.BooleanField()),
                ('donations_link', models.CharField(blank=True, max_length=200)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='child.Contact')),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='location',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='time_uploaded',
        ),
        migrations.AddField(
            model_name='organization',
            name='site',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='vacancies',
        ),
        migrations.AddField(
            model_name='program',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.Organization'),
        ),
    ]
