# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0010_auto_20180604_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.Organization'),
        ),
    ]
